# Milestone 2

## Installation of Packages

In [39]:
# Importing dataset - Food Supply Quantity (kg)
import pandas as pd
foodsupplykg = pd.read_csv('C:\\Users\\lyuen\\OneDrive\\desktop\\Data301\\Project\\project-group28-project\\data\\raw\\Food_Supply_Quantity_kg_Data.csv')
foodsupplykcal = pd.read_csv('C:\\Users\\lyuen\\OneDrive\\desktop\\Data301\\Project\\project-group28-project\\data\\raw\\Food_Supply_kcal_Data.csv')

In [30]:
foodsupplykg

,Country,Alcoholic Beverages,Animal fats,Animal Products,"Aquatic Products, Other",Cereals - Excluding Beer,Eggs,"Fish, Seafood",Fruits - Excluding Wine,Meat,...,Vegetables,Vegetal Products,Obesity,Undernourished,Confirmed,Deaths,Recovered,Active,Population,Unit (all except Population)
0,Afghanistan,0.0014,0.1973,9.4341,0.0000,24.8097,0.2099,0.0350,5.3495,1.2020,...,6.7642,40.5645,4.5,29.8,0.142134,0.006186,0.123374,0.012574,38928000.0,%
1,Albania,1.6719,0.1357,18.7684,0.0000,5.7817,0.5815,0.2126,6.7861,1.8845,...,11.7753,31.2304,22.3,6.2,2.967301,0.050951,1.792636,1.123714,2838000.0,%
2,Algeria,0.2711,0.0282,9.6334,0.0000,13.6816,0.5277,0.2416,6.3801,1.1305,...,11.6484,40.3651,26.6,3.9,0.244897,0.006558,0.167572,0.070767,44357000.0,%
3,Angola,5.8087,0.0560,4.9278,0.0000,9.1085,0.0587,1.7707,6.0005,2.0571,...,2.3041,45.0722,6.8,25,0.061687,0.001461,0.056808,0.003419,32522000.0,%
4,Antigua and Barbuda,3.5764,0.0087,16.6613,0.0000,5.9960,0.2274,4.1489,10.7451,5.6888,...,5.4495,33.3233,19.1,NaN,0.293878,0.007143,0.190816,0.095918,98000.0,%
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
165,Venezuela (Bolivarian Republic of),2.5952,0.0403,14.7565,0.0000,12.9253,0.3389,0.9456,7.6460,3.8328,...,4.1474,35.2416,25.2,21.2,0.452585,0.004287,0.424399,0.023899,28645000.0,%
166,Vietnam,1.4591,0.1640,8.5765,0.0042,16.8740,0.3077,2.6392,5.9029,4.4382,...,11.9508,41.4232,2.1,9.3,0.002063,0.000036,0.001526,0.000501,96209000.0,%
167,Yemen,0.0364,0.0446,5.7874,0.0000,27.2077,0.2579,0.5240,5.1344,2.7871,...,3.2135,44.2126,14.1,38.9,0.007131,0.002062,0.004788,0.000282,29826000.0,%
168,Zambia,5.7360,0.0829,6.0197,0.0000,21.1938,0.3399,1.6924,1.0183,1.8427,...,3.4649,43.9789,6.5,46.7,0.334133,0.004564,0.290524,0.039045,18384000.0,%
169,Zimbabwe,4.0552,0.0755,8.1489,0.0000,22.6240,0.2678,0.5518,2.2000,2.6142,...,2.3213,41.8526,12.3,51.3,0.232033,0.008854,0.190964,0.032214,14863000.0,%

In [31]:
foodsupplykcal

,Country,Alcoholic Beverages,Animal Products,Animal fats,"Aquatic Products, Other",Cereals - Excluding Beer,Eggs,"Fish, Seafood",Fruits - Excluding Wine,Meat,...,Vegetable Oils,Vegetables,Obesity,Undernourished,Confirmed,Deaths,Recovered,Active,Population,Unit (all except Population)
0,Afghanistan,0.0000,4.7774,0.8504,0.0,37.1186,0.1501,0.0000,1.4757,1.2006,...,2.3012,0.7504,4.5,29.8,0.142134,0.006186,0.123374,0.012574,38928000.0,%
1,Albania,0.9120,16.0930,1.0591,0.0,16.2107,0.8091,0.1471,3.8982,3.8688,...,2.8244,2.7508,22.3,6.2,2.967301,0.050951,1.792636,1.123714,2838000.0,%
2,Algeria,0.0896,6.0326,0.1941,0.0,25.0112,0.4181,0.1195,3.1805,1.2543,...,5.7638,2.0457,26.6,3.9,0.244897,0.006558,0.167572,0.070767,44357000.0,%
3,Angola,1.9388,4.6927,0.2644,0.0,18.3521,0.0441,0.8372,2.3133,2.9302,...,4.2741,0.3525,6.8,25,0.061687,0.001461,0.056808,0.003419,32522000.0,%
4,Antigua and Barbuda,2.3041,15.3672,1.5429,0.0,13.7215,0.2057,1.7280,3.6824,7.0356,...,4.6904,1.2960,19.1,NaN,0.293878,0.007143,0.190816,0.095918,98000.0,%
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
165,Venezuela (Bolivarian Republic of),0.8454,7.2303,0.6007,0.0,21.3126,0.2892,0.4449,2.3804,3.1368,...,7.5417,0.6674,25.2,21.2,0.452585,0.004287,0.424399,0.023899,28645000.0,%
166,Vietnam,0.7150,10.9806,0.9363,0.0,26.9833,0.2894,1.0385,1.8046,7.8311,...,1.3279,1.9578,2.1,9.3,0.002063,0.000036,0.001526,0.000501,96209000.0,%
167,Yemen,0.0000,3.4667,0.3394,0.0,32.0727,0.1455,0.1697,1.1879,2.0121,...,3.9515,0.3636,14.1,38.9,0.007131,0.002062,0.004788,0.000282,29826000.0,%
168,Zambia,1.1925,3.3043,0.3230,0.0,31.5528,0.1988,0.5714,0.2236,1.5155,...,3.0062,0.4472,6.5,46.7,0.334133,0.004564,0.290524,0.039045,18384000.0,%
169,Zimbabwe,1.4269,3.9356,0.6904,0.0,29.8044,0.1381,0.1611,0.4373,1.7491,...,6.2601,0.2532,12.3,51.3,0.232033,0.008854,0.190964,0.032214,14863000.0,%

In [2]:
### Supply food data descriptions

pd.read_csv('C:\\Users\\lyuen\\OneDrive\\desktop\\Data301\\Project\\project-group28-project\\data\\raw\\Supply_Food_Data_Descriptions.csv')

,Categories,Items
0,Alcoholic Beverages,"Alcohol, Non-Food; Beer; Beverages, Alcoholic;..."
1,Animal fats,"Butter, Ghee; Cream; Fats, Animals, Raw; Fish,..."
2,Animal Products,"Aquatic Animals, Others; Aquatic Plants; Bovin..."
3,"Aquatic Products, Other","Aquatic Animals, Others; Aquatic Plants; Meat,..."
4,Cereals - Excluding Beer,"Barley and products; Cereals, Other; Maize and..."
5,Eggs,Eggs
6,"Fish, Seafood",Cephalopods; Crustaceans; Demersal Fish; Fresh...
7,Fruits - Excluding Wine,"Apples and products; Bananas; Citrus, Other; D..."
8,Meat,"Bovine Meat; Meat, Other; Mutton & Goat Meat; ..."
9,Milk - Excluding Butter,Milk - Excluding Butter
10,Miscellaneous,Infant food; Miscellaneous
11,Offals,"Offals, Edible"
12,Oilcrops,Coconuts - Incl Copra; Cottonseed; Groundnuts ...
13,Pulses,"Beans; Peas; Pulses, Other and products"
14,Spices,"Cloves; Pepper; Pimento; Spices, Other"
15,Starchy Roots,Cassava and products; Potatoes and products; R...
16,Stimulants,Cocoa Beans and products; Coffee and products;...
17,Sugar & Sweeteners,Honey; Sugar (Raw Equivalent); Sugar non-centr...
18,Sugar Crops,Sugar beet; Sugar cane
19,Treenuts,Nuts and products
20,Vegetable Oils,Coconut Oil; Cottonseed Oil; Groundnut Oil; Ma...
21,Vegetables,"Onions; Tomatoes and products; Vegetables, Other"
22,Vegetal Products,"Alcohol, Non-Food; Apples and products; Banana..."

In [72]:
foodsupplykg_cleaned = food_supply[['Country','Stimulants','Confirmed','Deaths','Recovered','Active','Population']].rename(columns = {'Stimulants' : 'Stimulants (kg)'})
foodsupplykg_cleaned

,Country,Stimulants (kg),Confirmed,Deaths,Recovered,Active,Population
0,Afghanistan,0.3078,0.142134,0.006186,0.123374,0.012574,38928000.0
1,Albania,0.1055,2.967301,0.050951,1.792636,1.123714,2838000.0
2,Algeria,0.2216,0.244897,0.006558,0.167572,0.070767,44357000.0
3,Angola,0.0508,0.061687,0.001461,0.056808,0.003419,32522000.0
4,Antigua and Barbuda,0.1564,0.293878,0.007143,0.190816,0.095918,98000.0
...,...,...,...,...,...,...,...
165,Venezuela (Bolivarian Republic of),0.1479,0.452585,0.004287,0.424399,0.023899,28645000.0
166,Vietnam,0.2880,0.002063,0.000036,0.001526,0.000501,96209000.0
167,Yemen,0.2199,0.007131,0.002062,0.004788,0.000282,29826000.0
168,Zambia,0.0618,0.334133,0.004564,0.290524,0.039045,18384000.0
169,Zimbabwe,0.1494,0.232033,0.008854,0.190964,0.032214,14863000.0

In [73]:
foodsupplykcal_cleaned = foodsupplykcal[['Country','Stimulants','Confirmed','Deaths','Recovered','Active','Population']].rename(columns = {'Stimulants' : 'Stimulants (kcal)'})
fskcal_cleaned = foodsupplykcal_cleaned[['Stimulants (kcal)']]
fskcal_cleaned

     Stimulants (kcal)
0               0.0750
1               0.2501
2               0.1493
3               0.0441
4               0.4937
..                 ...
165             0.0667
166             0.1021
167             0.1212
168             0.0248
169             0.0460

[170 rows x 1 columns]

In [64]:
# There are some missing row values for confirmed, deaths, recovered, and active covid cases
print(foodsupplykg_cleaned.count(axis='rows'))
print(foodsupplykcal_cleaned.count(axis='rows'))

Country       170
Stimulants    170
Confirmed     164
Deaths        164
Recovered     164
Active        162
Population    170
dtype: int64
Country       170
Stimulants    170
Confirmed     164
Deaths        164
Recovered     164
Active        162
Population    170
dtype: int64

In [100]:
# Double check interpretations of units. Is it meant to be converted to a percentage or is it already a percentage (a low one)
foodsupply = pd.concat([foodsupplykg_cleaned, fskcal_cleaned], axis = 1)
foodsupply_x100 = foodsupply.iloc[:,[1,2,3,4,5,7]].multiply(100)
foodsupply

,Country,Stimulants (kg),Confirmed,Deaths,Recovered,Active,Population,Stimulants (kcal)
0,Afghanistan,0.3078,0.142134,0.006186,0.123374,0.012574,38928000.0,0.0750
1,Albania,0.1055,2.967301,0.050951,1.792636,1.123714,2838000.0,0.2501
2,Algeria,0.2216,0.244897,0.006558,0.167572,0.070767,44357000.0,0.1493
3,Angola,0.0508,0.061687,0.001461,0.056808,0.003419,32522000.0,0.0441
4,Antigua and Barbuda,0.1564,0.293878,0.007143,0.190816,0.095918,98000.0,0.4937
...,...,...,...,...,...,...,...,...
165,Venezuela (Bolivarian Republic of),0.1479,0.452585,0.004287,0.424399,0.023899,28645000.0,0.0667
166,Vietnam,0.2880,0.002063,0.000036,0.001526,0.000501,96209000.0,0.1021
167,Yemen,0.2199,0.007131,0.002062,0.004788,0.000282,29826000.0,0.1212
168,Zambia,0.0618,0.334133,0.004564,0.290524,0.039045,18384000.0,0.0248
169,Zimbabwe,0.1494,0.232033,0.008854,0.190964,0.032214,14863000.0,0.0460

In [ ]:
"""
Notes to self:

- Add a new column of population recovered based on percentage given in recovered and population of each country.
- Figure out a way to deal with missing values for covid related parameters.
- Think about how to best represent the data visually.

"""